includes/class-wcmp-rest-api-integration.php, woocommerce-myparcel.php
I implemented the changes that I proposed in issue #26 
There might be a better way to implement the addition of the custom data to the order but I could not find a better action or filter to hook in the WooCommerce code.
The code only works for the most recent version of the WooCommerce API that uses the Wordpress REST API.
This API was added in WooCommerce 2.6.0.
We only activate the new class when a version greater than 2.6.0 is used.
=> Add myparcel fields to REST api create order request

wpm-config.json
Adds support for [WP-Multilang](https://wordpress.org/plugins/wp-multilang/). This allows the delivery options (e.g. 'Delivered at home or at work') to be translated to multiple languages.
This wpm-config.json file is automatically detected by WP-Multilang. It will add a language switcher on top of the MyParcel-settings page. The settings can be stored in multiple languages.
=> Add wpm-config.json

includes/frontend/class-wcmp-cart-fees.php, package-lock.json, package.json
Steps to reproduce issue this PR + myparcelnl/delivery-options#45 will fix:
1. Select a shipping method that allows delivery options
2. Select morning delivery   
3. Morning delivery and only recipient fee are added to the checkout
4. Switch to a shipping method that does **not** allow delivery options 
5. The fees mentioned in step 4 are not removed
With these updates the fees should properly "refresh" across shipping methods.
=> Remove extra fees on switching shipping methods

migration/wcmp-upgrade-migration-v4-1-0.php
The url to autoload.php changed in migration file
=> fix: url for old vendor map

includes/admin/OrderSettings.php, includes/admin/class-wcmypa-admin.php
- `0` can't be saved into the database
- check for age check is not always true or null.
=> fix: export age check with setting of product

includes/admin/class-wcmp-api.php, includes/admin/class-wcmp-export.php
- LastShipmentIds is taken from the meta, there is no bool in it, but it is either empty or filled.
- If an order has an error, the order status will not have to be changed
=> fix: export order with incorrect shipment

includes/admin/class-wcmp-api.php, includes/admin/class-wcmp-export.php
track trace mail must be sent as soon as a barcode is known (printed). Only then can the status changed.
=> fix: barcode in email with order status automation

includes/admin/OrderSettings.php, includes/admin/OrderSettingsRows.php, includes/admin/class-wcmp-export-consignments.php, includes/admin/class-wcmp-export.php, includes/admin/class-wcmypa-admin.php, includes/admin/settings/class-wcmp-settings-data.php, includes/admin/settings/class-wcmp-shipping-methods.php, includes/admin/views/html-order-return-shipment-options.php, includes/admin/views/html-order-shipment-summary.php, includes/admin/views/html-send-return-email-form.php, includes/frontend/class-wcmp-checkout.php, languages/woocommerce-myparcel-en_GB.po, languages/woocommerce-myparcel-fr_BE.po, languages/woocommerce-myparcel-nl_BE.po, languages/woocommerce-myparcel-nl_NL.po, languages/woocommerce-myparcel.pot
- save weight in extraOptions['weight'] instead of own meta key
- never save converted weight over original weight
- save delivery options weight separately, don't overwrite actual order weight anymore
- fixes the following PHP warning:
> Invalid argument supplied for foreach() in /includes/admin/settings/class-wcmp-shipping-methods.php on line 213
=> fix: handle weight in a more robust manner

includes/admin/class-wcmypa-admin.php
This fixes an issue with incorrectly displayed HTML on the thank you page
=> Fix HTML typo in generateThankYouConfirmation

includes/frontend/class-wcmp-frontend.php
Fixes the PDF Invoices & Packing Slips part of #491 (see https://github.com/myparcelnl/woocommerce/issues/491#issuecomment-805881978)
=> Fix: show full delivery options for {{myparcel_delivery_options}}

composer.lock, includes/admin/settings/class-wcmp-settings-data.php, includes/admin/settings/class-wcmypa-settings.php, includes/frontend/class-wcmp-checkout.php, languages/woocommerce-myparcel-en_GB.po, languages/woocommerce-myparcel-en_US.po, languages/woocommerce-myparcel-fr_BE.po, languages/woocommerce-myparcel-fr_FR.po, languages/woocommerce-myparcel-nl_BE.po, languages/woocommerce-myparcel-nl_NL.po, languages/woocommerce-myparcel.pot
Added a list (select) with 'map' and 'list' in the settings checkout settings tab below 'show prices as', default 'map'
added method getPickupLocationsDefaultView() in class-wcmp-checkout to yield this value
translation strings added in google sheet: settings_pickup_locations_default_view, settings_pickup_locations_map, settings_pickup_locations_list
=> My 27832 deliveryoptions map or list default

includes/admin/class-wcmp-export.php, includes/frontend/class-wcmp-checkout.php
- fix: Warning: Invalid argument supplied for foreach() on class-wcmp-checkout.php on line 428
- the method `find_order_shipping_classes` is no longer needed because the shipping class is fetched through the `getShippingMethod`
=> fix: errors about empty shipping class

composer.json, includes/admin/class-wcmp-country-codes.php
Originele ticket ging over Saint Martin, daarbij zagen we dat de method isAllowedDestination altijd true teruggaf, omdat isWorldShippingCountry eigenlijk niet het land controleerde. Nu doet ie dat wel.
Eerste commit heeft dus een misleidende naam. Tevens: deze is afhankelijk van een wijziging in de SDK, vandaar de aanpassing in composer.json.
=> My 28149 fix isworldshipmentcountry returns false when country does not exist

includes/frontend/class-wcmp-checkout.php
Existing method expanded to also not show the options when only virtual products are in the cart
=> Feat: only show delivery options with non-virtual product in order

includes/admin/settings/class-wcmp-settings-data.php, includes/class-wcmp-data.php, includes/frontend/class-wcmp-cart-fees.php, languages/woocommerce-myparcel-en_GB.po, languages/woocommerce-myparcel-en_US.po, languages/woocommerce-myparcel-fr_BE.po, languages/woocommerce-myparcel-fr_FR.po, languages/woocommerce-myparcel-nl_BE.po, languages/woocommerce-myparcel-nl_NL.po
De change in `WCMP_Cart_Fees::getFeeTitles` is de echte fix, ik kon het gewoon niet laten om meteen de vertalingen strings mee te nemen :)
Resolves #648
=> fix: additional fees not being added to totals if delivery options titles are empty

includes/admin/class-wcmp-export.php
Issue: https://wordpress.org/support/topic/meta-field-returns-1-ipv-array/
=> fix: check if package type is set in _myparcel_shipment_options meta

includes/admin/class-wcmp-export.php
When calling `getShipmentData` with an empty list of IDs, all order would be retrieved, instead of not returning any orders. This has in some cases led to multiple shipments being assigned to an order that does not belong to this order.
By checking if the IDs list is empty before getting the orders from the API, and immediately returning an empty array in this case, the problem is solved.
=> Fix bug where getShipmentData would return all orders

includes/admin/OrderSettings.php, includes/admin/class-wcmypa-admin.php
There are several scenarios that don't work because the last value is always selected, when you use multiple products.
That is why an array is used.
=> fix: age check with different scenarios

includes/admin/class-wcmypa-admin.php
When a product is created, country of origin must be set to default. At the moment it will be set on Afghanistan.
- Resolves #686
=> fix: when a product is created, country of origin must be set to default

includes/adapter/RecipientFromWCOrder.php
- This fix ensures that orders remain visible in the order grid and that it is possible to change the address.
- Resolves #781
=> fix: error when it is not possible to split an address

readme.txt
Ik zag dat de vorige versie ook niet meegekomen was, bij deze is de readme up to date, volgende keer waarschijnlijk automatisch tijdens de release :-D
=> docs: update changelog

src/Migration/Pdk/SettingsMigration.php
Note: this would most likely not fail on production, but it will fail when the php error level is to show E_NOTICES
=> fix(migration): allow shipping method without colon

includes/admin/settings/class-wcmp-shipping-methods.php
Resolves https://wordpress.org/support/topic/fatal-error-if-woocommerce-table-rate-shipping-is-updated/
INT-453
=> fix(compatibility): restore compatibility with wooc table rate

src/Hooks/CheckoutScriptHooks.php, tests/Mock/MockWcCart.php, tests/Mock/MockWpEnqueue.php, tests/Unit/Hooks/CheckoutScriptHooksTest.php, tests/__snapshots__/ProductSettingsMigrationTest__it_migrates_pre_v5.0.0_product_settings_with_data_set_simple_product_with_all_settings__1.json, tests/mock_wp_functions.php
=> fix(checkout): use show delivery options on backorders setting

src/Pdk/Audit/Repository/WcPdkAuditRepository.php, tests/Mock/MockWcPdkAuditRepository.php, tests/Mock/MockWcPdkBootstrapper.php, tests/Unit/Pdk/Plugin/Repository/WcPdkAuditRepositoryTest.php
=> perf(orders): fix audits table being queried for each order in overview

src/Adapter/LegacyDeliveryOptionsAdapter.php, src/Pdk/Plugin/Repository/PdkOrderRepository.php
=> feat: find order by api identifier

src/Hooks/TaxFieldsHooks.php
INT-778
Make VAT and EORI fields optional for non-EU checkout
=> fix: Make VAT and EORI fields optional for non-EU checkout

src/Pdk/Service/LanguageService.php, tests/mock_wp_functions.php
fixes the myparcel settings screen in the admin always showing in the site default language, rather than any user-specific language override, and failing to show at all in any unsupported language
fixes INT-875
=> fix(language): fix myparcel settings not rendering in some languages

CONTRIBUTING.md, composer.json, composer.lock, src/Migration/Migration5_3_2.php, src/Pdk/Audit/Repository/WcPdkAuditRepository.php, src/Pdk/Plugin/Installer/WcMigrationService.php, tests/__snapshots__/EntryTest__it_adds_all_hooks_on_plugin_init__1.json, tests/__snapshots__/EntryTest__it_instantiates_the_plugin__1.json, tests/__snapshots__/SettingsMigrationTest__it_migrates_pre_v5.0.0_settings_with_data_set_empty__1.json, tests/__snapshots__/SettingsMigrationTest__it_migrates_pre_v5.0.0_settings_with_data_set_filled__1.json, woocommerce-myparcel.php
database migrations only ran when activating the plugin, this commit makes sure they are automatically checked when wordpress is loaded
fixes INT-876
=> fix(migrations): fix an issue where db migrations would not automatically run for already active plugin installations

views/frontend/common/src/types.ts, views/frontend/common/src/utils/checkout/getClassicCheckoutConfig.ts
fixes validation errors during checkout for street not being filled when the "split address" feature was enabled
fixes INT-716
=> fix(checkout): fix validation error when using split address

src/Pdk/WcPdkBootstrapper.php
=> fix: allow woocommerce emails by not throwing invalid argument exception
