myparcelnl/woocommerce

includes/class-wcmp-export.php
Because this code conflicts, I delete this code to make a new version. This codes will be made again, but without there are being any errors.
=> delete channel_engine code

includes/class-wcmp-admin.php
provides smoother upgrade from 1.X to latest version
=> support legacy consignment and tracktrace data

assets/delivery-options/js/myparcel.js
Open postnl pickup point details bij click
=> checkout postnl details hover

assets/css/nl-checkout.css, assets/delivery-options/js/myparcel.js, includes/class-wcmp-frontend-settings.php, includes/class-wcmp-frontend.php, includes/class-wcmp-settings.php, includes/views/wcmp-delivery-options-template.php
Add a header to the delivery options as title
=> Delivery options title

includes/class-wcmp-export.php, woocommerce-myparcel.php
#127 after creating shipment set track & trace code and shipping method as PostNL in channel engine's meta data
=> #127 Channel Engine Support

includes/class-wcmp-frontend-settings.php
this problem only occurs when using a windows server
=> fix error message about money_format

includes/class-wcmp-nlpostcode-fields.php
Solved issue with WooCommerce 3.5.1. 
Message: 
`Notice: Undefined index: priority in /Applications/MAMP/htdocs/woocommerce/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 1526`
=> add the priority to the checkout field

includes/class-wcmp-nlpostcode-fields.php, includes/views/wcmp-bulk-options-form.php
=> fix-php-5.4-compatibility

assets/js/myparcel.js, assets/js/wcmp-frontend.js, includes/class-wcmp-export.php, includes/class-wcmp-nl-postcode-fields.php
* Fix address field 2 being used wrong, now sends it to street_additional_info as expected
* Fix loader not showing on changing address
=> Fixes from feedback

assets/js/myparcel.js, assets/js/wcmp-frontend.js, includes/class-wcmp-settings.php
* fix delivery options not showing or updating after switching country back to NL/BE* 
* fix link to monday delivery info
* fix pickup express never showing (+whitespace)
=> Feedback 27-11

assets/js/wcmp-frontend.js, readme.txt, woocommerce-myparcel.php
When the form already filled in, there is no update. When you change the country, than there will be a update.
=> remove is_updated check

assets/js/myparcel.js
=> standard-delivery-text

assets/js/myparcel.js
=> change input to click

assets/js/myparcel.js, includes/class-wcmp-frontend-settings.php, readme.txt, woocommerce-myparcel.php
=> Fix delivery date when deliveryday window is 0 

includes/class-wcmp-frontend.php
Add translation to housenumber and add value to again button
issue: [230](https://github.com/myparcelnl/woocommerce/issues/230)
=> addTranslationToHousenumberUnknown

includes/class-wcmp-admin.php
[231](https://github.com/myparcelnl/woocommerce/issues/231) Disable delivery date in orderview for Belgium shipments
=> Show deliveryday only for nl

includes/class-wcmp-frontend-settings.php
#143 Set default to 0 if there's no tax rate set up
=> Set default to 0 if there's no tax rate set up

includes/class-wcmp-export.php
fix issue with shipping class term id
=> fix issue with shipping class term id

includes/class-wcmp-export.php
Cut the product title after 60 characters
Features: #190
=> Cut the product title after 50 characters

includes/class-wcmp-export.php
#240 Correct amount on the digital stamp label
=> Correct amount on the digital stamp

includes/class-wcmp-export.php
#229  trying to get property of non-object error has solved with add (int) before the variable
=> trying to get property of non-object

includes/class-wcmp-export.php
#244 Shipment validation error by PakjeGemak with return option
=> fix for pakjegemak with return shipment

assets/js/wcmp-frontend.js
Clear the extra options in the total cart when changing the shipping method.
=> Shipping method issue with pickup

includes/class-wcmp-export.php
use constants for delivery_type
=> use constants for delivery_type

includes/class-wcmp-admin.php
#264 Zoeken naar barcode in het orderoverzicht
=> Add search fields to order grid

includes/class-wcmp-export.php
https://github.com/myparcelnl/woocommerce/issues/265
=> add max 5 items to shipment for world shipments

assets/js/myparcel.js, assets/js/wcmp-admin.js, includes/class-wcmp-admin.php, includes/class-wcmp-export.php, includes/class-wcmp-frontend.php, includes/class-wcmp-settings.php, languages/woocommerce-myparcel-nl_NL.po, languages/woocommerce-myparcel.pot, readme.txt, templates/wcmp-delivery-options-template.php, woocommerce-myparcel.php
It is no longer possible to use pickup express, since November
=> Remove Pickup Express

includes/admin/views/html-order-shipment-summary.php, includes/frontend/class-wcmp-cart-fees.php
signature is the first element in the array. When signature is not selected he always returns. The fee of Only recipient is never added.
=> fix Only recipient fee

includes/admin/class-wcmp-admin.php, includes/admin/settings/class-wcmp-settings-data.php, includes/admin/settings/class-wcmp-settings.php
Add option for show delivery date so you can set days on/off
=> Add option for show delivery date 

includes/admin/class-wcmp-export-consignments.php, includes/admin/views/html-bulk-options-form.php
Add empty parcel weight option
https://jira.dmp.zone/browse/MY-22315
=> Add empty parcel weight option

assets/css/wcmp-admin-styles.css, assets/js/wcmp-admin.js, includes/admin/class-wcmp-admin.php, includes/admin/class-wcmp-export.php, includes/admin/views/html-order-shipment-options.php
=> fix html layout of shipment summary and settings and fix searching in woo orders overview

includes/class-wcmp-data.php
=> when deliveryType is empty use default package

includes/admin/settings/class-wcmp-settings-data.php, includes/admin/settings/class-wcmypa-settings.php, includes/frontend/class-wcmp-checkout.php, migration/wcmp-upgrade-migration-v4-0-8.php, woocommerce-myparcel.php
- adds options that were missing in 4.0.0
- rename at_home_delivery to delivery_title
- fix monday delivery
Fixes #433
=> Add 4.0.8 settings migration

includes/admin/class-wcmp-export.php
=> Uncaught TypeError for getPackageTypeFromOrder

migration/wcmp-upgrade-migration-v4-0-0.php, migration/wcmp-upgrade-migration-v4-1-0.php, migration/wcmp-upgrade-migration.php, package-lock.json
* fix: support receiving falsy values from get_option in migrations to fix fatal errors
This occurs when settings entries don't exist at all. This can happen if the user for example never visited and saved one of the settings tabs.
=> Fix 4.1.0 migration fatal errors

includes/admin/class-wcmp-export-consignments.php
Change the check from datetime to date
=> Fix error: data.shipments[0].options.delivery_date delivery_date is too early

includes/admin/class-wcmp-export.php
=> Fix missing barcode in automatically processed emails

includes/admin/settings/class-wcmp-settings-data.php, includes/entities/settings-field-arguments.php, src/js/.eslintrc, src/js/wcmp-admin.js
=> ESLint everything 

includes/admin/class-wcmp-export.php, includes/admin/views/html-order-return-shipment-options.php, includes/admin/views/html-order-shipment-options.php, includes/admin/views/html-send-return-email-form.php, includes/admin/views/html-start.php, includes/class-wcmp-assets.php, src/js/wcmp-admin.js, src/scss/admin/_helpers.scss, src/scss/admin/_index.scss, src/scss/admin/_shipment-options-dialog.scss, src/scss/admin/_shipment-summary.scss, src/scss/wcmp-admin-styles.scss
- package types now work
- weights are correct
- style updated
=> fix: send return email modal

includes/collections/settings-collection.php, includes/frontend/class-wcmp-cart-fees.php, includes/frontend/class-wcmp-checkout.php
…and pass the user selected option names to woocommerce fees
Closes #429
=> feat: add taxes to delivery options prices when needed

.eslintrc, .gitignore, composer.lock, gulpfile.js, includes/admin/settings/class-wcmp-settings-data.php, languages/woocommerce-myparcel-en_GB.po, languages/woocommerce-myparcel-fr_BE.po, languages/woocommerce-myparcel-nl_BE.po, languages/woocommerce-myparcel.pot, package-lock.json, package.json, private/convertCsvToPo.js, private/createTimestamp.js, private/downloadFile.js, private/downloadTranslations.js, private/importTranslations.js, private/mergeCsvTranslations.js
- import from google sheets
The downside: You need to install translate toolkit to use the translation importing/exporting functionality at the moment. 
```sh
brew install translate-toolkit
```
More instructions here: http://docs.translatehouse.org/projects/translate-toolkit/en/latest/installation.html
=> feat: better translations!

includes/frontend/class-wcmp-checkout.php, src/js/wcmp-frontend.js
=> fix(checkout): show correct prices when switching between shipping methods

includes/admin/OrderSettingsRows.php, includes/admin/class-wcmp-country-codes.php, includes/admin/class-wcmp-export-consignments.php, readme.txt
- older code reverted to ensure quality.
=> hotfix: the selection between the world and the EU is not going well

includes/class-wcmp-postcode-fields.php
=> fix ship_to_different_address check in validation

includes/admin/OrderSettings.php, includes/admin/class-wcmp-export.php
There is also a check if the minimum insurance or higher has been chosen on the basis of the carrier.
Required: https://github.com/myparcelnl/sdk/pull/298
=> Fix: insurance is not properly saved.

includes/admin/class-wcmypa-admin.php
Show delivery type only when myparcel delivery options are enabled
=> Show delivery type only when myparcel delivery options are enabled

src/js/wcmp-frontend.js
=> fix: use type hidden to hide the delivery options input. 

js/auto_menu.js
toevoeging window.location aan auto_menu.js zodat url wordt gebruikt en op id's kan worden gezocht
=> window.location toevoeging

includes/admin/class-wcmp-export.php, includes/admin/class-wcmypa-admin.php
=> Fix: set-mailbox-shipments-outside-NL-to-Package

composer.lock, includes/admin/class-wcmp-export-consignments.php, includes/admin/class-wcmp-export.php, includes/class-wcmp-data.php, languages/woocommerce-myparcel-en_GB.po, languages/woocommerce-myparcel-en_US.po, languages/woocommerce-myparcel-fr_BE.po, languages/woocommerce-myparcel-fr_FR.po, languages/woocommerce-myparcel-nl_BE.po, languages/woocommerce-myparcel-nl_NL.po, languages/woocommerce-myparcel.pot
The validate function will trap errors in consignments (no HS code, no weight) and specifically weight errors for entire orders, and remove the offending order from the bulk action, so the api most likely will not complain.
=> My 28141 friendlier error messages

includes/admin/class-wcmp-export-consignments.php, includes/admin/class-wcmp-export.php
Added hooks to let plugins change the label description and run functions on successfully exporting labels.
=> Added some hooks

src/js/wcmp-admin.js
=> fix: double export when using the bulk actions 2

language/nl_NL.html
removed jpg and edited a sentence
=> Fix: remove-jpg-and-sentence

includes/admin/class-wcmp-export.php
=> fix: allow old shipping methods in order

includes/admin/class-wcmp-export-consignments.php
Depends on SDK change myparcelnl/sdk#367
=> feat: add region to consignment when exporting

includes/Helper/LabelDescriptionFormat.php, includes/adapter/OrderLineFromWooCommerce.php, includes/admin/class-wcmp-export.php, includes/admin/views/html-send-return-email-form.php
=> fix: fix errors caused by deleted products

includes/admin/OrderSettingsRows.php, includes/admin/class-wcmypa-admin.php, includes/admin/settings/Status.php, includes/admin/settings/class-wcmypa-settings.php, includes/class-wcmp-data.php, includes/frontend/class-wcmp-checkout.php, readme.txt
=> refactor(instabox): rename rjp to instabox

includes/class-wcmp-postcode-fields.php
fix(checkout): allow 6 characters as number suffix
Resolves #789
=> fix(checkout): allow 6 characters as number suffix

includes/admin/class-wcmp-export.php
=> fix: the weight calculations must be multiplied

includes/admin/class-wcmp-export-consignments.php, includes/admin/class-wcmypa-admin.php, includes/frontend/class-wcmp-checkout.php
Reverts myparcelnl/woocommerce#816
=> fix: revert only show delivery date in order view when necessary

includes/adapter/delivery-options-from-order-adapter.php, includes/admin/class-wcmp-export.php, includes/class-wcmp-data.php
=> fix(om): error when delivery options absent

includes/admin/class-wcmp-export.php
=> fix: php warnings undefined array key

includes/admin/OrderSettings.php
=> fix: remove age check from eu and row consignments

includes/frontend/class-wcmp-checkout.php
=> fix: tablerate plugin mailbox

includes/admin/views/html-order-shipment-summary.php, src/js/wcmp-admin.js
=> fix: fix track trace link in order summary

woocommerce-myparcel.php
=> fix: prevent external translations

includes/admin/OrderSettings.php
=> fix: fix digital stamp default weight

includes/frontend/class-wcmp-frontend-track-trace.php
=> fix: remove barcode from refund mail

includes/admin/OrderSettings.php, includes/admin/class-wcmypa-admin.php
=> feat: show digital stamp weight in order view

includes/admin/class-wcmp-export.php, includes/admin/views/MyParcelWidget.php
=> feat: add modal option for myparcel orders only

includes/admin/class-wcmp-export.php
=> fix: show order detail even when package type is integer

includes/admin/class-wcmypa-admin.php, includes/admin/settings/class-wcmp-shipping-methods.php, includes/collections/settings-collection.php
=> fix: fix several type errors

includes/admin/class-wcmypa-admin.php
=> fix: close inline style properly

src/js/wcmp-frontend.js
=> fix: allow delivery options with partial address

composer.lock, package.json, yarn.lock
- update @myparcel/delivery-options to 5.7.1
https://github.com/myparcelnl/delivery-options/releases/tag/v5.7.1
=> fix(checkout): do not show address inputs when allowRetry is false

package.json, src/js/wcmp-frontend.js, yarn.lock
Needs myparcelnl/delivery-options#177
=> fix(checkout): fix showing address errors before address is filled in

composer.lock, package.json, yarn.lock
https://github.com/myparcelnl/delivery-options/releases/tag/v5.7.4
=> chore(deps): update @myparcel/delivery-options to 5.7.4

composer.lock, config/pdk.php, src/Pdk/Hooks/PdkProductSettingsHooks.php, src/Pdk/Product/Repository/WcPdkProductRepository.php, src/Pdk/Service/WcFrontendRenderService.php, src/Pdk/Service/WcViewService.php, tests/Mock/MockWcProductVariation.php, tests/Unit/Pdk/Hooks/PdkProductSettingsHooksTest.php, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_BE_order__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_EU_order__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_ROW_order__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_order_with_all_shipment_options__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_order_with_saved_delivery_options__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_order_with_saved_notes__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_simple_order__1.json, tests/mock_class_map.php, views/backend/admin/src/assets/scss/_woocommerce.scss, views/backend/admin/src/components/WcDescription.vue, views/backend/admin/src/components/WcHelpTip.vue, views/backend/admin/src/components/pdk/WcChildProductSettingsFormGroup.vue, views/backend/admin/src/components/pdk/WcFormGroup.vue, views/backend/admin/src/components/pdk/WcProductSettingsFormGroup.vue, views/backend/admin/src/components/pdk/WcToggleInput.vue, views/backend/admin/src/components/pdk/index.ts, views/backend/admin/src/composables/index.ts, views/backend/admin/src/composables/useElementData.ts, views/backend/admin/src/initialize.ts, yarn.lock
=> feat(product): support variation product settings

views/backend/admin/src/assets/scss/_woocommerce.scss, views/backend/admin/src/components/pdk/WcBox.vue, views/backend/admin/src/components/pdk/WcModal.vue, views/backend/admin/src/components/pdk/WcShipmentLabelWrapper.vue
- prevents dragging of single order box to avoid responsiveness issues
=> fix(admin): make the boxes and modals match wordpress better

src/Migration/Pdk/OrdersMigration.php, src/Migration/Pdk/ProductSettingsMigration.php, tests/Mock/WordPressOptions.php, tests/Mock/WordPressScheduledTasks.php, tests/Unit/Migration/Pdk/OrdersMigrationTest.php, tests/Unit/Service/WpCronServiceTest.php, tests/Uses/UsesMockWcPdkInstance.php, tests/mock_class_map.php
- also correct chunk counts in logs
=> refactor(migration): use cron service

src/Adapter/WcAddressAdapter.php, tests/Mock/MockWcCustomer.php, tests/Mock/MockWcOrder.php, tests/Unit/Adapter/WcAddressAdapterTest.php, tests/__snapshots__/WcAddressAdapterTest__it_creates_address_from_WC_Cart_with_data_set_billing_address__1.yml, tests/__snapshots__/WcAddressAdapterTest__it_creates_address_from_WC_Cart_with_data_set_german_address__1.yml, tests/__snapshots__/WcAddressAdapterTest__it_creates_address_from_WC_Customer_with_data_set_billing_address__1.yml, tests/__snapshots__/WcAddressAdapterTest__it_creates_address_from_WC_Customer_with_data_set_german_address__1.yml, tests/__snapshots__/WcAddressAdapterTest__it_creates_address_from_WC_Order_with_data_set_german_address__1.yml, tests/__snapshots__/WcAddressAdapterTest__it_creates_address_from_WC_Order_with_data_set_vat_fields__1.yml
- use billing address if there is no shipping address
- pass state correctly
=> fix(orders): fix state and missing address fields errors

src/Pdk/Plugin/Repository/PdkOrderRepository.php, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_BE_order__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_EU_order__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_ROW_order__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_order_with_all_shipment_options__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_order_with_saved_delivery_options__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_order_with_saved_notes__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_simple_order__1.json, tests/factories/WC_Order_Factory.php
=> feat(order): support digital stamp weight range option

src/Migration/AbstractMigration.php, src/Migration/Pdk/OrdersMigration.php, src/Migration/Pdk/ProductSettingsMigration.php, src/Pdk/Plugin/Repository/PdkOrderRepository.php, src/Pdk/Plugin/Repository/WcOrderNoteRepository.php, src/Pdk/Product/Repository/WcPdkProductRepository.php, tests/Mock/MockWcClass.php
=> fix(orders): fix storing data in hpos

.idea/inspectionProfiles/Project_Default.xml, .idea/myparcelnl-woocommerce.iml, src/Pdk/Hooks/PdkCoreHooks.php, src/Pdk/Hooks/PdkPluginSettingsHooks.php, tests/__snapshots__/EntryTest__it_adds_all_hooks_on_plugin_init__1.json
=> fix(admin): show correct styling in settings page

src/Adapter/WcAddressAdapter.php, tests/Unit/Adapter/WcAddressAdapterTest.php
=> fix(orders): fix error when state does not match XX-XX format

src/Migration/AbstractMigration.php, src/Migration/Pdk/OrdersMigration.php, src/Migration/Pdk/ProductSettingsMigration.php, src/Pdk/Product/Repository/WcPdkProductRepository.php, tests/Mock/MockWcClass.php, tests/Mock/MockWcProduct.php
=> fix(product-settings): fix updating without hpos

src/Hooks/Concern/UsesPdkRequestConverter.php
=> fix(webhooks): use json params

src/Pdk/WcPdkBootstrapper.php, tests/Mock/MockWpUser.php, tests/Unit/Pdk/WcPdkBootstrapperTest.php, tests/mock_wp_functions.php
=> fix(permissions): check all user roles

src/Hooks/RanWebhookActions.php, src/Hooks/WebhookActions.php, src/Pdk/WcPdkBootstrapper.php, src/Service/WordPressHookService.php, src/Service/WpCronService.php, tests/Datasets/callbacks.php, tests/Mock/MockCallableClass.php, tests/Mock/MockWcPdkBootstrapper.php, tests/Mock/MockWpActions.php, tests/Mock/WordPressOptions.php, tests/Unit/Hooks/WebhookActionsTest.php, tests/Unit/Service/WpCronServiceTest.php, tests/functions.php, tests/mock_wp_functions.php, woocommerce-myparcel.php
=> fix(cronservice): make callable usable

includes/admin/settings/CarrierSettings.php, includes/class-wcmp-data.php, migration/wcmp-upgrade-migration-v4-22-0.php, woocommerce-myparcel.php
INT-270
1 JANUARI AANPASSING, NIET MERGEN
=> feat: change digital stamp weight range

includes/Helper/ExportRow.php
=> fix(order-mode): fix item value on customs declaration

includes/admin/class-wcmypa-admin.php
=> fix(tracktrace): use correct url for foreign shipments

src/Pdk/Hooks/PdkCoreHooks.php, src/Service/WpScriptService.php, views/backend/admin/vite.config.ts
=> feat: update to latest delivery options

src/Hooks/CheckoutScriptHooks.php, tests/__snapshots__/EntryTest__it_adds_all_hooks_on_plugin_init__1.json
=> fix(checkout): have delivery options show in classic checkout

views/backend/admin/src/components/pdk/WcDropOffInput.vue
=> fix(admin): fix dropoff input not showing

woocommerce-myparcel.php
=> feat: add hpos incompatibility warning

src/Migration/Migration5_0_0_beta_9.php, src/Migration/Pdk/SettingsMigration.php, src/Pdk/Plugin/Installer/WcMigrationService.php, tests/Unit/Migration/Migration5_0_0_beta_9Test.php, tests/Unit/Migration/Pdk/SettingsMigrationTest.php, tests/__snapshots__/SettingsMigrationTest__it_migrates_pre_v5.0.0_settings_with_data_set_filled__1.json, views/backend/admin/src/assets/scss/_woocommerce.scss, views/backend/admin/src/components/pdk/WcFormGroup.vue, views/backend/admin/src/components/pdk/WcSelectInput.vue, views/backend/admin/src/components/pdk/WcTable.vue, views/backend/admin/src/components/pdk/WcTableCol.vue, views/backend/admin/src/initialize.ts, views/backend/admin/tailwind.config.cjs, views/frontend/checkout-core/src/main.ts
=> feat: allow picking package type per shipping method

views/backend/admin/src/components/pdk/WcDropdownButton.vue
=> fix(admin): fix button dropdowns not expanding correctly

private/semantic-release/header-beta.md, woocommerce-myparcel.php
=> chore: name plugin conforming to wordpress guidelines

src/Pdk/Hooks/PdkWebhookHooks.php, src/Pdk/Plugin/Action/WcWebhookService.php, src/Pdk/WcPdkBootstrapper.php, tests/Mock/MockWcClass.php, tests/Mock/MockWpClass.php, tests/Mock/MockWpRestRequest.php, tests/Mock/MockWpRestResponse.php, tests/Mock/MockWpRestServer.php, tests/Mock/MocksGettersAndSetters.php, tests/Unit/Pdk/Hooks/PdkWebhookHooksTest.php, tests/Uses/UsesMockWcPdkInstance.php, tests/mock_class_map.php, tests/mock_wp_functions.php
=> fix(webhooks): fix webhooks not working

composer.json, includes/class-wcmp-data.php, includes/frontend/class-wcmp-checkout.php, package.json
=> feat: add support for small package

src/Hooks/Concern/UsesPdkRequestConverter.php, src/Logger/WcLogger.php, src/Pdk/Hooks/AbstractPdkEndpointHooks.php, src/Pdk/Hooks/PdkAdminEndpointHooks.php, src/Pdk/Hooks/PdkFrontendEndpointHooks.php
=> feat(backend): add download logs action

src/Service/WpCronService.php, tests/Mock/MockCallableClass.php, tests/Unit/Service/WpCronServiceTest.php
=> fix(webhooks): prevent webhook callback never being executed

package.json
Use the latest delivery options
=> feat: allow delivery date for carrier dhlforyou

includes/frontend/class-wcmp-checkout.php
=> fix: fix small package not showing in delivery options

includes/admin/class-wcmp-export.php
=> feat: add filter before consignment export

README.md
=> docs: clarify limitations of third-party checkout limitations

readme.txt, tests/Unit/Integration/DeliveryOptionsBlocksIntegrationTest.php
=> chore: fix typos

includes/admin/OrderSettings.php, includes/admin/OrderSettingsRows.php, includes/admin/class-wcmp-export-consignments.php, includes/admin/class-wcmp-export.php, includes/admin/settings/CarrierSettings.php, includes/admin/settings/class-wcmypa-settings.php
=> feat: add receipt code for WooCommerce v4

src/Hooks/AddressWidgetHooks.php, src/Hooks/CheckoutScriptHooks.php
=> feat(address): only load the address widget if enabled in settings

src/Adapter/WcAddressAdapter.php, src/Hooks/AddressWidgetHooks.php
Use the stored JSON object for the address whenever available
Fixes INT-947
=> feat: send address data to API

package.json, views/backend/admin/package.json, views/blocks/delivery-options/package.json, views/frontend/checkout-address-widget/src/utils/init.ts, views/frontend/checkout-core/package.json, views/frontend/checkout-delivery-options/package.json, views/frontend/checkout-separate-address-fields/package.json, views/frontend/checkout-tax-fields/package.json, yarn.lock
force all js-pdk packages to their latest versions to resolve issues with getting the pdk instance in admin pages
=> fix(admin): resolve issues with loading some form components in admin

readme.txt
=> docs: remove flespakket

src/Pdk/Plugin/Repository/PdkOrderRepository.php, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_BE_order__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_EU_order__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_ROW_order__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_order_with_all_shipment_options__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_order_with_saved_delivery_options__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_order_with_saved_notes__1.json, tests/__snapshots__/PdkOrderRepositoryTest__it_creates_a_valid_pdk_order_with_data_set_simple_order__1.json
=> fix: correct price when exporting order

package.json, yarn.lock
fixes an issue where the generated autoload / autoload_static.php contained non-namespaced classes
fixes #1338, INT-1043
=> fix: fix conflicting class names in autoload

views/backend/admin/src/main.ts
Resolves: [INT-1077](https://internal.jira.dmp.zone/browse/INT-1077)
[INT-1077]: https://myparcelnl.atlassian.net/browse/INT-1077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: improve javascript compatibility with other plugins
